apps/baenangtalk/urls.py
from django.urls import path
from apps.baenangtalk import views
from .views import *

app_name='baenangtalk'

urlpatterns = [
    # 배낭톡
    path('', MainPostListView.as_view(), name='bae_main'), 
    path('detail/<int:pk>/', PostDetailView.as_view(), name='bae_detail'), 
    path('create/', PostCreateView.as_view(), name='bae_create'),  
    path('eidt/<int:pk>/', PostEditView.as_view(), name='bae_edit'),  
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='bae_delete'),  
    
    path('city/<int:county_id>/', MainPostListView.as_view(), name='city_posts'),  # 도시 선택
    path('period/<int:period_id>/', MainPostListView.as_view(), name='period_posts'),  # 여행시기 선택
    path('subject/<int:subject_id>/', MainPostListView.as_view(), name='subject_posts'),  # 주제 선택
    
    # 좋아요&취소
    path('like/<int:pk>/', views.bae_post_like, name='bae_like'),  
    path('unlike/<int:pk>/', views.bae_post_unlike, name='bae_unlike'),  

    # 댓글
    path('com/eidt/<int:comment_id>/', views.com_edit, name='com_edit'),  
    path('com/delete/<int:comment_id>/', views.com_delete, name='com_delete'),  
    # 댓글 좋아요&취소
    path('com/like/<int:comment_id>/', views.com_like, name='com_like'),  
    path('com/unlike/<int:comment_id>/', views.com_unlike, name='com_unlike'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.travel.urls")),

    path('mypage/', login_required(TemplateView.as_view(template_name='mypage.html')), name='mypage'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', login_required(TemplateView.as_view(template_name='profile.html')), name='profile'),
    # path('  /', login_required(TemplateView.as_view(template_name='profile.html')), name='profile'),

    path('baenangtalk/', include("apps.baenangtalk.urls")),
    path('flights/',include('apps.flights.urls',namespace='flights')),
    path('chatbot/', include('apps.chatbot.urls')),
    path('plan/', include('apps.plan.urls')),
    path('planrecommend/', include('apps.planrecommend.urls')),
    # path('tour/', include('apps.tour.urls')),
    path('customer_service/', include('apps.customer_service.urls')),
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/baenangtalk/models.py
from django.db import models
from apps.travel.models import County
from apps.userinfo.models import User

# 배낭톡 주제
class BaenangtalkSubject(models.Model):
    bae_sub_name = models.CharField('주제명', max_length=10)  # 배낭톡 주제

    def __str__(self):
        return self.bae_sub_name
    

# 배낭톡 여행시기
class BaenangtalkPeriod(models.Model):
    bae_month = models.DateField('월')  # 배낭톡 여행시기

    def __str__(self):
        return self.bae_month.strftime('%m')
    

# 배낭톡
class Baenangtalk(models.Model):
    county = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name='도시')  # 도시 모델 외부키
    period = models.ForeignKey(BaenangtalkPeriod, on_delete=models.CASCADE, verbose_name='여행시기')  # 여행시기 모델 외부키
    subject = models.ForeignKey(BaenangtalkSubject, on_delete=models.CASCADE, verbose_name='주제')  # 주제 모델 외부키
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저 모델 외부키
    bae_title = models.CharField('제목', max_length=100)  # 배낭톡 제목
    bae_content = models.TextField('내용')  # 배낭톡 본문
    bae_img = models.ImageField('이미지', upload_to='baenangtalk/img')  # 배낭톡 이미지
    bae_like = models.IntegerField('좋아요', default=0)  # 배낭톡 좋아요
    bae_like_by = models.ManyToManyField(User, related_name='liked_posts')  # 좋아요 누른 회원
    bae_date = models.DateTimeField('작성일', auto_now_add=True)  # 작성일

    def __str__(self):
        return self.bae_title


# 배낭톡 댓글
class BaenangtalkComment(models.Model):
    bae = models.ForeignKey(Baenangtalk, on_delete=models.CASCADE)  # 배낭톡 모델 외부키
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 유저 모델 외부키
    bae_com_content = models.CharField(max_length=100)  # 댓글내용
    bae_com_like = models.IntegerField('좋아요', default=0)  # 좋아요
    bae_com_like_by = models.ManyToManyField(User, related_name='liked_comments')  # 좋아요를 누른 회원 
    bae_com_date = models.DateTimeField('작성일', auto_now_add=True)  # 작성일 

    def __str__(self):
        return self.bae_com_content

apps/baenangtalk/forms.py
from django import forms
from .models import *

# 배낭톡 ##############################################################################

# 게시글 작성
class BaenangtalkForm(forms.ModelForm):
    class Meta:
        model = Baenangtalk
        fields = ['county', 'period', 'subject', 'bae_title', 'bae_content', 'bae_img']
        labels = {
            'county': '도시',
            'period': '여행시기',
            'subject': '주제',
            'bae_title': '제목',
            'bae_content': '내용',
            'bae_img': '이미지'
        }


# 게시글 수정
class BaenangtalkForm(forms.ModelForm):
    class Meta:
        model = Baenangtalk
        fields = ['county', 'period', 'subject', 'bae_title', 'bae_content', 'bae_img']

# 댓글 ##############################################################################

# 댓글 작성
class CommentcreateForm(forms.ModelForm):
    class Meta:
        model = BaenangtalkComment
        fields = ['bae_com_content']

# 댓글 수정
class CommentEditForm(forms.ModelForm):
    class Meta:
        model = BaenangtalkComment
        fields = ['bae_com_content']
        labels = {
            'bae_com_content': '',  # 레이블을 빈 문자열로 설정
        }

# 댓글 삭제
class CommentDeleteForm(forms.ModelForm):
    class Meta:
        model = BaenangtalkComment
        fields = []

apps/baenangtalk/views.py
from .models import *
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import * 
from django.contrib.auth.decorators import login_required

# 배낭톡 main + post ##############################################################################

# 배낭톡 main
class MainPostListView(ListView):
    model = Baenangtalk
    template_name = 'bae_main.html'
    context_object_name = 'posts'

    def get_queryset(self):
        # 모든 객체 가져오기
        queryset = Baenangtalk.objects.all() 

        # URL에서 전달된 county_id, period_id, subject_id 가져오기
        county_id = self.request.GET.get('county_id')  
        period_id = self.request.GET.get('period_id') 
        subject_id = self.request.GET.get('subject_id') 

        # 필터링 조건 추가
        if county_id:
            queryset = queryset.filter(county_id=county_id)
        if period_id:
            queryset = queryset.filter(period_id=period_id)
        if subject_id:
            queryset = queryset.filter(subject_id=subject_id)

        # 내림차순 정렬
        return queryset.order_by('-bae_date')

    # 템플릿에 전달할 data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # URL에서 전달된 county_id, period_id, subject_id 가져오기
        county_id = self.request.GET.get('county_id') 
        period_id = self.request.GET.get('period_id')  
        subject_id = self.request.GET.get('subject_id')  

        if county_id:
            context['selected_county'] = County.objects.get(pk=county_id)
        if period_id:
            context['selected_period'] = BaenangtalkPeriod.objects.get(pk=period_id)
        if subject_id:
            context['selected_subject'] = BaenangtalkSubject.objects.get(pk=subject_id)

        if county_id:
            context['county_id'] = int(county_id)
        if period_id:
            context['period_id'] = int(period_id)
        if subject_id:
            context['subject_id'] = int(subject_id)

        # 모든 county 가져오기
        context['counties'] = County.objects.all()
        # 모든 여행시기 가져오기
        context['periods'] = BaenangtalkPeriod.objects.all()
        # 모든 주제 가져오기
        context['subjects'] = BaenangtalkSubject.objects.all()

        return context
    

# 배낭톡 detail
class PostDetailView(DetailView):
    template_name = 'post/bae_detail.html'

    def get(self, request, pk):
        baenangtalk = get_object_or_404(Baenangtalk, pk=pk)  # Baenangtalk 객체 가져오기
        comments = BaenangtalkComment.objects.filter(bae=baenangtalk)  # BaenangtalkComment 객체 가져오기
        form = CommentcreateForm()  # 댓글 폼 초기화

        # 템플릿으로 전달할 data 
        context = {
            'profile': baenangtalk.user.profile,
            'nickname': baenangtalk.user.username,
            'period': baenangtalk.period.bae_month,
            'county': baenangtalk.county.city_name,
            'subject': baenangtalk.subject.bae_sub_name,
            'bae_title': baenangtalk.bae_title,
            'bae_img': baenangtalk.bae_img,
            'bae_content': baenangtalk.bae_content,
            'bae_date': baenangtalk.bae_date,
            'bae_like': baenangtalk.bae_like,
            'form': form,
            'comments': comments,
            'baenangtalk': baenangtalk 
        }

        return render(request, self.template_name, context)

    # POST 요청 처리
    def post(self, request, pk):
        baenangtalk = get_object_or_404(Baenangtalk, pk=pk)  
        form = CommentcreateForm(request.POST)
        # 입력된 데이터 유효성 검사
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user  # 요청을 보낸 사용자 = 댓글의 작성자
            comment.bae = baenangtalk  # 해당 댓글이 속한 게시글 설정
            comment.save()  # DB 저장
            return redirect('baenangtalk:bae_detail', pk=pk)
        else:
            comments = BaenangtalkComment.objects.filter(bae=baenangtalk)
            context = {
                'profile': baenangtalk.user.profile,
                'nickname': baenangtalk.user.username,
                'period': baenangtalk.period.bae_month,
                'county': baenangtalk.county.city_name,
                'subject': baenangtalk.subject.bae_sub_name,
                'bae_title': baenangtalk.bae_title,
                'bae_img': baenangtalk.bae_img,
                'bae_content': baenangtalk.bae_content,
                'bae_date': baenangtalk.bae_date,
                'bae_like': baenangtalk.bae_like,
                'form': form,
                'comments': comments,
                'baenangtalk': baenangtalk 
            }
            return render(request, self.template_name, context)
    

# 배낭톡 create
class PostCreateView(CreateView):
    template_name = 'post/bae_create.html'

    def get(self, request):
        form = BaenangtalkForm()  # 폼 인스턴스 생성
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = BaenangtalkForm(request.POST, request.FILES)  # POST 데이터와 파일 데이터를 받아 폼 인스턴스 생성

        if form.is_valid():
            # 폼이 유효하면 데이터 저장
            baenangtalk = form.save(commit=False)  # 데이터베이스에 바로 저장하지 않고 인스턴스 생성
            baenangtalk.user = request.user  # 현재 사용자를 작성자로 설정 
            baenangtalk.save()  # 데이터베이스에 저장

            # 게시글 작성 완료 후 리다이렉트
            return redirect('baenangtalk:bae_detail', pk=baenangtalk.pk)  # 작성된 게시글의 상세 페이지로 리다이렉트

        # 폼이 유효하지 않으면 다시 폼을 보여줌
        return render(request, self.template_name, {'form': form})


# 배낭톡 edit
class PostEditView(UpdateView):
    template_name = 'post/bae_edit.html'

    def get(self, request, pk):
        baenangtalk = get_object_or_404(Baenangtalk, pk=pk)

        # 현재 사용자가 작성자인지 확인
        if baenangtalk.user != request.user:
            return redirect('baenangtalk:bae_detail', pk=pk)

        form = BaenangtalkForm(instance=baenangtalk)
        return render(request, self.template_name, {'form': form, 'baenangtalk': baenangtalk})

    def post(self, request, pk):
        baenangtalk = get_object_or_404(Baenangtalk, pk=pk)

        # 현재 사용자가 작성자인지 확인
        if baenangtalk.user != request.user:
            return redirect('baenangtalk:bae_detail', pk=pk)

        form = BaenangtalkForm(request.POST, request.FILES, instance=baenangtalk)

        if form.is_valid():
            baenangtalk = form.save()

            # 수정 완료 후 리다이렉트
            return redirect('baenangtalk:bae_detail', pk=pk)

        # 폼이 유효하지 않으면 다시 폼을 보여줌
        return render(request, self.template_name, {'form': form, 'baenangtalk': baenangtalk})


# 배낭톡 delete
class PostDeleteView(DeleteView):
    model = Baenangtalk  # Baenangtalk 모델을 대상으로 한다고 명시
    template_name = 'post/bae_delete.html'

    def post(self, request, pk):
        baenangtalk = get_object_or_404(Baenangtalk, pk=pk)  # pk에 해당하는 Baenangtalk 객체 가져오기

        # 현재 사용자가 작성자인지 확인
        if baenangtalk.user == request.user:
            # 작성자일 경우 삭제
            baenangtalk.delete()

        # 삭제 후 리다이렉트할 URL 설정 
        return redirect('baenangtalk:bae_main') 


# 배낭톡 좋아요 ##############################################################################


# 배낭톡 게시글 좋아요
@login_required
def bae_post_like(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Baenangtalk, pk=pk)
        user = request.user  # 현재 로그인된 사용자

        if user not in post.bae_like_by.all():
            post.bae_like_by.add(user)
            post.bae_like += 1
            post.save()
        return redirect('baenangtalk:bae_detail', pk=pk)
        
    return redirect('baenangtalk:bae_detail', pk=pk)


# 배낭톡 게시글 좋아요 취소
@login_required
def bae_post_unlike(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Baenangtalk, pk=pk)
        user = request.user  # 현재 로그인된 사용자

        if user in post.bae_like_by.all():
            post.bae_like_by.remove(user)
            post.bae_like -= 1
            post.save()
        return redirect('baenangtalk:bae_detail', pk=pk)

    return redirect('baenangtalk:bae_detail', pk=pk)


# 댓글 ##############################################################################

# 댓글 수정
def com_edit(request, comment_id):
    comment = get_object_or_404(BaenangtalkComment, id=comment_id)
    
    if request.method == 'POST':
        form = CommentEditForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('baenangtalk:bae_detail', pk=comment.bae.pk) # 댓글이 수정된 후 게시글 상세페이지로 이동
    else:
        form = CommentEditForm(instance=comment)
    
    return render(request, 'comment/com_edit.html', {'form': form})



# 댓글 삭제
@login_required
def com_delete(request, comment_id):
    comment = get_object_or_404(BaenangtalkComment, id=comment_id)
    if request.method == 'POST':
        if comment.bae:  # comment.bae가 존재하는지 확인
            comment.delete()
            return redirect('baenangtalk:bae_detail', pk=comment.bae.pk)
        else:
            # 적절한 오류 메시지와 함께 다른 페이지로 리다이렉트
            messages.error(request, "관련 게시글이 존재하지 않습니다.")
            return redirect('baenangtalk:bae_main')  # 예를 들어 메인 페이지로 리다이렉트
    else:
        if comment.bae:
            return render(request, 'comment/com_delete.html', {'object': comment})
        else:
            messages.error(request, "관련 게시글이 존재하지 않습니다.")
            return redirect('baenangtalk:bae_main')



# 댓글 좋아요
@login_required
def com_like(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(BaenangtalkComment, id=comment_id)
        user = request.user  # 현재 로그인된 사용자


        if user not in comment.bae_com_like_by.all():
            comment.bae_com_like_by.add(user)
            comment.bae_com_like += 1
            comment.save()
        return redirect('baenangtalk:bae_detail', pk=comment.bae.pk)

    return redirect('baenangtalk:bae_detail', pk=comment.bae.pk)



# 댓글 좋아요 취소
@login_required
def com_unlike(request, comment_id):

apps/baenangtalk/templates/bae_main.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'baenangtalk/main.css' %}">
{% endblock %}
<div class="container mt-3">
    <a href="{% url 'baenangtalk:bae_main' %}">
        <h3 class="mb-4">배낭톡</h3>
    </a>
    
    <!-- 도시 선택 -->
    <div class="btn-group" style="text-align: right;">
        <button type="button" class="btn btn-outline-light btn-custom dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #0BD0AF; margin-right: 10px;">
            {% if county_id %}
                <strong>{{ selected_county.city_name }}</strong>
            {% else %}
                도시 선택
            {% endif %}
        </button>
        <div class="dropdown-menu">
            {% for county in counties %}
                <a class="dropdown-item" href="?county_id={{ county.id }}{% if period_id %}&period_id={{ period_id }}{% endif %}{% if subject_id %}&subject_id={{ subject_id }}{% endif %}">
                    {{ county.city_name }}
                </a>
            {% endfor %}
        </div>
    </div>

    <!-- 여행시기 선택 -->
    <div class="btn-group" style="text-align: right;">
        <button type="button" class="btn btn-outline-light btn-custom dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #0BD0AF; margin-right: 10px;">
            {% if period_id and selected_period %}
                <strong>{{ selected_period.bae_month|date:"M" }}</strong>
            {% else %}
                여행시기 선택
            {% endif %}
        </button>
        <div class="dropdown-menu">
            <!-- 각 여행시기 선택 항목 -->
            {% for period in periods %}
                <a class="dropdown-item{% if period.id == period_id %} active{% endif %}" href="?{% if county_id %}county_id={{ county_id }}&{% endif %}period_id={{ period.id }}{% if subject_id %}&subject_id={{ subject_id }}{% endif %}">
                    {{ period.bae_month|date:"M" }}
                </a>
            {% endfor %}
        </div>
    </div>


    <!-- 주제 선택 -->
    <div class="btn-group" style="text-align: right;">
        <button type="button" class="btn btn-outline-light btn-custom dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #0BD0AF;">
            {% if subject_id and selected_subject %}
                <strong>{{ selected_subject.bae_sub_name }}</strong>
            {% else %}
                주제 선택
            {% endif %}
        </button>
        <div class="dropdown-menu">
            <!-- 각 주제 선택 항목 -->
            {% for subject in subjects %}
                <a class="dropdown-item{% if subject.id == subject_id %} active{% endif %}" href="?{% if county_id %}county_id={{ county_id }}&{% endif %}{% if period_id %}period_id={{ period_id }}&{% endif %}subject_id={{ subject.id }}">
                    {{ subject.bae_sub_name }}
                </a>
            {% endfor %}
        </div>
    </div>

    <!-- 배낭톡 이용규칙 & 제안하기 & 작성 -->
    <div class="d-flex justify-content-end">
        <!-- 배낭톡 이용규칙 -->
        <div class="ms-3">
            <a href="#" class="bi bi-bell" id="create-post-btn"></a>
        </div>

        <!-- 배낭톡 제안하기 -->
        <div class="ms-3">
            <a href="#" class="bi bi-pencil-square" id="create-post-btn"></a>
        </div>

        <!-- 배낭톡 작성 -->
        <div class="ms-3">
            <a href="{% url 'baenangtalk:bae_create' %}" class="bi bi-pencil" id="create-post-btn"></a>
        </div>
    </div>

    <!-- 배낭톡 게시글 리스트 -->
    <div class="row">
        {% for post in posts %}
        <div class="mb-4">
            <div class="card">
                <!-- 이미지 -->
                <img src="{{ post.bae_img.url }}" class="card-img-top" style="height: 240px; object-fit: cover; object-position: center;" alt="{{ post.bae_title }}">
                <div class="card-body">
                    <!-- 제목 -->
                    <h5 class="card-title">
                        <a href="{% url 'baenangtalk:bae_detail' post.id %}">{{ post.bae_title }}</a>
                    </h5>
                    <!-- 내용 -->
                    <p class="card-text">{{ post.bae_content }}</p>
                    <!-- 좋아요 & 댓글 & 작성일 -->
                    <p class="card-text" style="display: flex; justify-content: space-between;">
                        <!-- 좋아요 & 댓글-->
                        <small>
                            <i class="bi bi-heart" style="color: red;"></i> {{ post.bae_like }}
                            <i class="bi bi-chat-dots" style="color: rgb(70, 70, 70); margin-left: 5px;"></i> {{ post.baenangtalkcomment_set.all.count }}
                        </small>
                        <!-- 작성일 -->
                        <small class="text-muted">{{ post.bae_date | date:"Y.m.d" }}</small>
                    </p> 
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <div class="alert alert-warning" role="alert">
                작성된 게시글이 없습니다.
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}