apps/accommodation/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'accommodation'

urlpatterns = [
    path('', AccommodationHomeView.as_view(), name='accommodation_home'),
    path('detail/<int:pk>/', AccomodationDetailView.as_view(), name='accommodation_detail'),
    path('detail/<int:accommodation_pk>/room/<int:room_pk>/', RoomDetailView.as_view(), name='room_detail'),
    path('detail/<int:pk>/map/', my_view, name='map'),
    path('reservation/<int:accommodation_pk>/room/<int:room_pk>/', make_reservation, name='create_reservation'),
    path('reservation/success/', reservation_success, name='reservation_success'),
    path('detail/<int:pk>/create_review/', CreateReview.as_view(), name='create_review'),
    path('detail/<int:accommodation_pk>/review/<int:review_pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('detail/<int:accommodation_pk>/review/<int:review_pk>/update/', UpdateReview.as_view(), name='update_review'),
    path('detail/<int:accommodation_pk>/review/<int:review_pk>/delete/', DeleteReview.as_view(), name='delete_review'),
    path('accommodations/<str:filter_type>/<str:filter_value>/', AccommodationFilterView.as_view(), name='accommodation_filter'),
    path('region_select/', region_select, name='region_select'),
    path('list/<str:accommodation_type>/',accommodation_type_region_select, name='accommodation_type_region_select'),
    path('list/<str:accommodation_type>/<str:city_name>/', accommodation_region_list, name='accommodation_region_list'),
    path('detail/<int:accommodation_pk>/like/', like_accommodation, name='like_accommodation'),
    path('detail/<int:accommodation_pk>/unlike/', unlike_accommodation, name='unlike_accommodation'),
    path('search_accommodations/', search_accommodations, name='search_accommodations'),
    # path('api/check_availability/', CheckAvailabilityAPI.as_view(), name='check_availability'),
    # path('search/', search_accommodations, name='accommodation_search'),

    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.travel.urls")),

    path('mypage/', login_required(TemplateView.as_view(template_name='mypage.html')), name='mypage'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', login_required(TemplateView.as_view(template_name='profile.html')), name='profile'),
    # path('  /', login_required(TemplateView.as_view(template_name='profile.html')), name='profile'),

    path('baenangtalk/', include("apps.baenangtalk.urls")),
    path('flights/',include('apps.flights.urls',namespace='flights')),
    path('chatbot/', include('apps.chatbot.urls')),
    path('plan/', include('apps.plan.urls')),
    path('planrecommend/', include('apps.planrecommend.urls')),
    # path('tour/', include('apps.tour.urls')),
    path('customer_service/', include('apps.customer_service.urls')),
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accommodation/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from apps.userinfo.models import User
from apps.travel.models import County

DOMESTIC_ACCOMMODATION_TYPES = (
    ('pension_pool_vila', '펜션, 풀빌라'),
    ('camping_glamping', '캠핑, 글램핑'),
    ('boutique_motel', '부티크 모텔'),
)

# 숙소 정보를 저장할 모델
class Accommodation(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    city = models.ForeignKey(County, on_delete=models.CASCADE)  # 도시 정보 참조
    location = models.CharField(max_length=100)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    accommodation_type = models.CharField(max_length=100, choices=DOMESTIC_ACCOMMODATION_TYPES, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    like = models.ManyToManyField(User, related_name='like_accommodations', blank=True)

    DOMESTIC_ACCOMMODATION_TYPES = (
        ('pension_pool_vila', '펜션, 풀빌라'),
        ('camping_glamping', '캠핑, 글램핑'),
        ('boutique_motel', '부티크 모텔'),
    )



# 숙소 이미지를 저장할 모델
class AccommodationImage(models.Model):
    accommodation = models.ForeignKey(Accommodation, related_name='images', on_delete=models.CASCADE)
    images = models.ImageField(upload_to='accommodation')

# 숙소 객실 정보 저장할 모델
class Room(models.Model):
    accommodation = models.ForeignKey(Accommodation, related_name='rooms', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    capacity = models.IntegerField()
    is_free_cancellation = models.BooleanField(default=False)
    includes_breakfast = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    check_in_time = models.TimeField()
    check_out_time = models.TimeField()
    guide = models.TextField(null=True, blank=True)  # 이용안내 필드 추가

    def __str__(self):
        return f"{self.name} - {self.accommodation.name}"
class RoomImage(models.Model):
    room = models.ForeignKey(Room, related_name='images', on_delete=models.CASCADE)
    images = models.ImageField(upload_to='room')

# 예약자 정보 모델
class ReservationHolderInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.user.email}"

# 예약 페이지에서 작성할 투숙자 정보 모델
class GuestInfo(models.Model):
    name = models.CharField(max_length=100)
    birth_date = models.DateField()
    gender = models.CharField(max_length=10, choices=(('male', '남성'), ('female', '여성')))


# 예약 페이지에서 작성할 교통편 정보 모델
class TransportationInfo(models.Model):
    public_transport = models.BooleanField(default=False)
    walking = models.BooleanField(default=False)
    personal_car = models.BooleanField(default=False)


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='accommodation_reservations')
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateField(blank=False, null=False) # 체크인 날짜
    check_out = models.DateField(blank=False, null=False)
    reservation_holder_info = models.OneToOneField(ReservationHolderInfo, on_delete=models.CASCADE)
    guest_info = models.OneToOneField(GuestInfo, on_delete=models.CASCADE)
    transportation_info = models.OneToOneField(TransportationInfo, on_delete=models.CASCADE)
    cancellation_policy_agreed = models.BooleanField(default=False)
    terms_and_conditions_agreed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True) 
    reservation_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    guests_adult = models.PositiveIntegerField(default=2)  # 성인 인원수 필드
    guests_child = models.PositiveIntegerField(default=0)  # 아동 인원수 필드
    telnum = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} - {self.accommodation.name}"


# 리뷰 작성하기 
class Review(models.Model):
    accommodation = models.ForeignKey(Accommodation, related_name='reviews', on_delete=models.CASCADE)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE,  null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)
    image_url = models.ImageField(upload_to='review', blank=True)
    travel_date = models.CharField(max_length=10,null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.accommodation.name}"

# 취소 및 이용 규정 모델
class CancellationPolicy(models.Model):
    policy_text = models.TextField()
    agree_text = models.TextField(null=True, blank=True)

class AccommodationLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accommodation = models.ForeignKey(Accommodation, related_name='likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/accommodation/forms.py
from django import forms
from .models import Review, Reservation
from apps.userinfo.models import User

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [ 'rating', 'travel_date','content', 'image_url']
        # widgets = {
        #     'rating': forms.RadioSelect(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        # }
        widgets = {
            'rating': forms.RadioSelect(choices=[
                (1, '1 Star'),
                (2, '2 Stars'),
                (3, '3 Stars'),
                (4, '4 Stars'),
                (5, '5 Stars')
            ]),
        }

from .models import Reservation, ReservationHolderInfo, GuestInfo, TransportationInfo

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['check_in', 'check_out', 'cancellation_policy_agreed', 'terms_and_conditions_agreed', 'guests_adult', 'guests_child', 'telnum']


class ReservationHolderInfoForm(forms.ModelForm):
    username = forms.CharField(max_length=150)
    email = forms.EmailField()
    telnum = forms.CharField(max_length=15)

    class Meta:
        model = ReservationHolderInfo
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ReservationHolderInfoForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['username'].initial = user.username
            self.fields['email'].initial = user.email

class GuestInfoForm(forms.ModelForm):
    class Meta:
        model = GuestInfo
        fields = ['name', 'birth_date', 'gender']

class TransportationInfoForm(forms.ModelForm):
    class Meta:
        model = TransportationInfo
        fields = ['public_transport', 'walking', 'personal_car']

apps/accommodation/templates/review/review_detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}{{review.user.username}}님의 리뷰{% endblock %}

{% block content %}
    <style>
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 30px 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        .button-container {
            max-width: 800px;
            display: flex;
    justify-content: flex-end;
        }
        .star-rating {
            font-size: 1em;
            color: #f5b301;
            margin: 20px 20px;
        }
        .review-content {
            margin-top: 20px;
        }
        .back-button {
            cursor: pointer;
            font-size: 32px;
            margin-right: auto;
            margin-top: -10px;
        }
        .header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            position: relative;
        }
        .uploaded-image {
            width: 750px;
            margin: 10px 0;
            text-align: center;
        }
        .uploaded-image img {
            width: 100%;
            height: auto;
            text-align: center;
            align-items: center;

            border: none;
        }
        .user-profile {
            display: flex;
            align-items: center;
            margin-top: 20px;
        }
        .user-profile img {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            margin-right: 10px;
            margin-left: 20px;
        }
        .user-info {
            display: flex;
            flex-direction: column;
        }
        .acommodation {
            display: flex;
            align-items: center; /* 수직 정렬을 가운데로 설정 */
            }

        .profile-image {
            width: 50px; /* 프로필 사진 크기로 설정 */
            height: 50px; /* 프로필 사진 크기로 설정 */
            border-radius: 8px; /* 원형으로 만들기 위해 추가 */
            object-fit: cover; /* 이미지가 잘리지 않도록 추가 */
            margin-right: 10px; /* 이미지와 텍스트 사이의 간격 추가 */
            margin-left: 20px;
        }

        
        .heart-button {
            border: none; /* 테두리 제거 */
            padding: 0; /* 내부 여백 제거 */
            margin: 0; /* 외부 여백 제거 */
            background: none; /* 배경색 제거 */
        }
       
        .heart {
            color: black; /* 기본 하트 색 */
            }
        .heart-fill {
            color: red; /* 좋아요 상태일 때 하트 색 */
 
        }
        .dropdown-menu {
            display: none;
            position: absolute;
            right: 0;
            top: 100%;
            z-index: 1000;
            float: left;
            min-width: 10rem;
            padding: .5rem 0;
            margin: .125rem 0 0;
            font-size: 1rem;
            color: #e9e9e9;
            text-align: left;
            list-style: none;
            /* background-color: #fff; */
            /* background-clip: padding-box; */
            border: none;
            /* border-radius: .25rem; */
        }

        .dropdown-menu.show {
            display: block;
            right: 0; /* 드롭다운 메뉴를 오른쪽으로 정렬 */
            left: auto; /* 기본 왼쪽 정렬을 비활성화 */
        }
        .dropdown {
            position: absolute;
            right: 0;
        }
        .dropdown-toggle {
            background-color: transparent;
            border: none;
            padding: 0;
        }
        .dropdown-toggle .bi-three-dots {
            color: #000000;
        }
        .dropdown-toggle:focus,
        .dropdown-toggle:active,
        .dropdown-toggle:focus:active {
            background-color: transparent !important;
            border: none !important;
            box-shadow: none !important;
        }
        .dropdown-toggle .bi-three-dots {
            color: #000000;
        }
    </style>
</head>
<body>
    <div class="container mt-4">
        <div class="header">
            <div class="d-flex align-items-center justify-content-between">
                <i class="bi bi-x back-button"></i>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" aria-expanded="false">
                        <i class="bi bi-three-dots"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                        <li><a class="dropdown-item" href="{% url 'accommodation:update_review' accommodation.pk review.pk %}">수정하기</a></li>
                        <li><a class="dropdown-item" onclick="deleteReview({{ accommodation.pk }}, {{ review.pk }})">삭제하기</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accommodation d-flex align-items-center">
            {% if images|length > 0 %}
                <img src="{{ MEDIA_URL }}{{ images.0.images }}" class="profile-image" alt="Accommodation Image" style="margin-right: 10px;">
            {% endif %}
            <div>
                <h5 style="font-weight: bold; margin-bottom: 0;">
                    <a href="{% url 'accommodation:accommodation_detail' accommodation.pk %}" style="text-decoration: none; color: inherit;">
                        {{ review.accommodation.name }}
                    </a>
                </h5>
                <span style="font-weight: bold; font-size: 14px;">{{ review.accommodation.city.city_name }}</span>
            </div>
            <div class="ml-auto" style="margin-left: 450px;">
                <button class="heart-button {% if accommodation_is_liked %}active{% endif %}">
                    <i class="bi bi-heart {% if is_liked %}heart-fill{% else %}heart{% endif %}" id="save-button" style="display: block; font-size: 24px; cursor: pointer;"></i>
                </button>
            </div>
        </div>
        
        <div class="user-profile">
            <img src="{{MEDIA_URL}}{{ review.user.profile }}" alt="User Profile Image">
            <div class="user-info">
                <span style="font-weight: bold;">{{ review.user.username }}</span>
                <span class="text-muted">({{ review.user.review_set.count }}개의 리뷰)</span>
            </div>
        </div>
        <div class="review-details">
            <div class="star-rating">
                
                {% for i in "12345" %}
                    {% if i|add:0 <= review.rating %}
                        <i class="fas fa-star"></i>
                    {% else %}
                        <i class="far fa-star"></i>
                    {% endif %}
                {% endfor %}
                

            </div>
            <div class="review-content">
                <p style="margin-left: 20px; font-weight: bold;">{{ review.content }}</p>
            </div>
            <div class="review-date">
                {% if review.travel_date %}
                    <small class="text-muted" style="margin-left: 20px;">{{ review.travel_date }}</small>
                {% endif %}
            </div>
            <!-- <div class="review-images">
                {% for image in review.images.all %}
                    <img src="{{MEDIA_URL}}{{ image.image_url }}" alt="Review Image" class="img-thumbnail" style="max-width: 150px; margin: 10px;">
                {% endfor %}
            </div> -->
            <div class="uploaded-image">
                {% if review.image_url %}
                    <img src="{{MEDIA_URL}}{{ review.image_url }}" alt="Uploaded Image" class="img-thumbnail">
                    <hr style="border: 10px solid #f0f0f0; margin-top: 0;">
                {% endif %}
            </div>
            
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function deleteReview(accommodationPk, reviewPk) {
        if (confirm('정말로 이 리뷰를 삭제하시겠습니까?')) {
            fetch(`/accommodation/detail/${accommodationPk}/review/${reviewPk}/delete/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = `/accommodation/detail/${accommodationPk}/`; // 삭제 후 리다이렉트할 URL
                } else {
                    return response.text().then(text => {
                        alert(text);
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('리뷰 삭제 중 오류가 발생했습니다.');
            });
        }
    }
        document.querySelector('.back-button').addEventListener('click', function() {
            window.location.href = '/accommodation/detail/{{ accommodation.pk }}/';
        });
        document.querySelector('.heart-button').addEventListener('click', function() {
            const icon = this.querySelector('i');
            if (icon.classList.contains('far')) {
                icon.classList.remove('far');
                icon.classList.add('fas');
            } else {
                icon.classList.remove('fas');
                icon.classList.add('far');
            }
        });
        document.addEventListener('DOMContentLoaded', function() {
            const dropdownButton = document.getElementById('dropdownMenuButton');
            const dropdownMenu = document.querySelector('.dropdown-menu');

            dropdownButton.addEventListener('click', function() {
                dropdownMenu.classList.toggle('show');
            });

            document.addEventListener('click', function(event) {
                if (!dropdownButton.contains(event.target) && !dropdownMenu.contains(event.target)) {
                    dropdownMenu.classList.remove('show');
                }
            });
        });

        document.getElementById('save-button').addEventListener('click', function() {
            var isLiked = this.classList.contains('heart-fill');
            var url = isLiked ? '/accommodation/detail/{{ accommodation.pk }}/unlike/' : '/accommodation/detail/{{ accommodation.pk }}/like/';
        
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ 'accommodationId': '{{ accommodation.pk }}' })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'ok') {
                    if (isLiked) {
                        // 좋아요 취소 처리
                        this.classList.remove('heart-fill');
                        document.getElementById('save-text').className = 'button-save';
                    } else {
                        // 좋아요 처리
                        this.classList.add('heart-fill');
                        document.getElementById('save-text').className = 'button-cancel';
                    }
                }
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        });
                    
</script>
{% endblock %}